# Generated by Django 4.2.2 on 2023-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_razorpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='razorpay',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='razorpay',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
