# Generated by Django 4.2.2 on 2023-07-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_razorpay_order_id_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpay',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='razorpay',
            name='signature',
        ),
    ]
