# Generated by Django 4.2.2 on 2023-07-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_razorpay_payment_id_remove_razorpay_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpay',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='razorpay',
            name='signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
