# Generated by Django 4.2.2 on 2023-07-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_razorpay_payment_id_razorpay_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpay',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='razorpay',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='razorpay',
            name='signature',
        ),
    ]
